# Generated by Django 4.2.1 on 2024-12-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='agent',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto de Portada'),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(blank=True, max_length=50, verbose_name='Puesto/Rol'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
