version: '3'

services:
  appherreradb:
      container_name: appherreradb
      image: postgres:13.0
      environment:
        - POSTGRES_USER=appherrera
        - POSTGRES_PASSWORD=appherrerapass
        - POSTGRES_DB=appherreradb
      expose: 
        - 5432
      ports:
        - 5432:5432
  appherreraweb:
      container_name: appherreraweb
      build: .
      command: 'python3 manage.py runserver 0.0.0.0:8000'
      volumes:
        - .:/app
      ports:
        - '8000:8000'
      env_file:
        - '.env'
      depends_on:
        - appherreradb
