version: '3'

services:
  appherreradb:
      container_name: appherreradb
      image: postgres:13.0
      environment:
        - POSTGRES_USER=appherrera
        - POSTGRES_PASSWORD=appherrerapass
        - POSTGRES_DB=appherreradb
      expose:
        - 5432
  appherreraweb:
      container_name: appherreraweb
      build: .
      command: 'python3 manage.py runserver 0.0.0.0:8000'
      volumes:
        - .:/app
      expose:
        - 8000
      env_file:
        - '.env'
      depends_on:
        - appherreradb
  web_nginx:
        container_name: web_nginx
        build: ./nginx
        ports:
            - 80:80
            - 443:443
