# Generated by Django 4.2.1 on 2024-10-04 01:24

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Portada')),
                ('lead', models.CharField(max_length=255, verbose_name='Lead')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
                ('slug_category', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Portada')),
                ('lead', models.CharField(max_length=255, verbose_name='Lead')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
                ('slug_type', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Portada')),
                ('image_2', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Contenido')),
                ('video', models.URLField(blank=True, default=None, null=True, verbose_name='Youtube URL')),
                ('definicion', models.TextField(blank=True, default=None, null=True, verbose_name='Definición')),
                ('beneficio', models.TextField(blank=True, default=None, null=True, verbose_name='Beneficio')),
                ('elegibilidad', models.TextField(blank=True, default=None, null=True, verbose_name='Elegibilidad')),
                ('exepciones', models.TextField(blank=True, default=None, null=True, verbose_name='Excepciones')),
                ('adicionales', models.TextField(blank=True, default=None, null=True, verbose_name='Adicionales')),
                ('caracteristicas', models.TextField(blank=True, default=None, null=True, verbose_name='Caracteristicas')),
                ('slug_product', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='entities.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='entities.type'),
        ),
    ]
