# Generated by Django 4.2.1 on 2024-10-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fav',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Favorito'),
        ),
    ]
