name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/git:latest

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build Docker Image
        run:
          docker build  -t ${{ vars.APP_NAME }}:latest .
          docker save ${{ vars.APP_NAME }}:latest > ${{ vars.APP_NAME }}.tar
          chmod 664 ${{ vars.APP_NAME }}.tar
      -
        name: Transfer Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_HG }}
          username: ${{ secrets.SSH_USERNAME_HG }}
          key: ${{ secrets.SSH_KEY_HG }}
          port: ${{ secrets.SSH_PORT_HG }}
          source: ${{ vars.APP_NAME }}.tar
          target: "/tmp"
      - 
        name: Load Docker image on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_HG }}
          username: ${{ secrets.SSH_USERNAME_HG }}
          key: ${{ secrets.SSH_KEY_HG }}
          port: ${{ secrets.SSH_PORT_HG }}
          script: |
            docker load -i /tmp/${{ vars.herreradocker }}.tar
            docker stop ${{ vars.herreradocker }} || true
            docker rm ${{ vars.herreradocker }} || true
            docker run -d -p ${{ secrets.SSH_PORT_HG }} --name ${{ vars.herreradocker }} ${{ vars.herreradocker }}:latest
           





